# Header
menu:
  home:
    text: Home
    url: /
  archives:
    text: Archives
    url: /archives/
  th-list:
    text: Categories
    url: /categories/
  tags:
    text: Tags
    url: /tags/
  github:
    text: Github
    url: https://github.com/cksachdev
    target : _blank  
  info-circle:
    text: About me
    url: /about/

# Read More text
excerpt_link: Read More