# hexo-theme-indigo-plus
# https://github.com/abelsu7/hexo-theme-indigo-plus

# Add new menu items following the rules below
# menu:
#  link:              Font Awesome icon，omit the prefix，this topic is prefixed with icon-，have to

#    text: About      The text displayed in the menu, if omitted, the default  is the same as the icon, and the first letter will be capitalized 

#    url: /about      Links, absolute or relative paths, must be.
#    target: _blank   Whether to jump out, omit to open on the current page
menu:
  home:
    text: Home
    url: /
  archives:
    text: Archives
    url: /archives/
  th-list:
    text: Categories
    url: /categories/
  tags:
    text: Tags
    url: /tags/
  github:
    text: Github
    url: https://github.com/cksachdev
    target : _blank  
  info-circle:
    text: About me
    url: /about/

# Your avatar url
avatar: /img/cksachdev.jpg
# avatar link
avatar_link: /

# Avatar background image
brand: /img/black-bg-img.jpeg
# favicon
favicon: /img/favicon.ico

# email
email: mail@chetansachdev.com

# set up Android L Chrome Browser status bar color
color: '#3F51B5'

# page title
tags_title: Tags
archives_title: Archives
categories_title: Categories

# atricle truncation
excerpt_render: true
excerpt_length: 200
excerpt_link: Read more...
mathjax: true
archive_yearly: true

# last update time of article
show_last_updated: true

# sharing
share: true

# reward
reward: false
# reward:
#   title:Thanks for the support！
#   wechat: /img/wechat.png     #wechat，close to false
#   alipay: /img/alipay.jpg     #alipay，close to false

# search
search: true

# navigation
hideMenu: true

# open toc
# toc: false
toc:
  list_number: false  # numeric sorting

# article page message content，hexo all variables and auxiliary functions can be called，for details, please refer tohexo.io
postMessage: Article publishing address：<a href="<%- url_for(page.path).replace(/index\.html$/, '') %>" target="_blank" rel="external"><%- page.permalink.replace(/index\.html$/, '') %></a>

# webmaster statistics, if you want to open, enter the CNZZ site id, such as cnzz: 1255152447
cnzz: false

# baidu statistics, if you want to open, change to yours key
baidu_tongji: false
baidu_site_verification: false
# Baidu automatic push, if you want to open, set to true
baidu_push: false

# tencent analysis, if you want to open, enter the site id
tajs: false

# google
google_analytics: UA-3044287-8
google_site_verification: true

# sogou webmaster verification http://zhanzhang.sogou.com/
sogou_site_verification: false

# less
less:
  compress: true
  paths:
    - source/css/style.less

# the following comment plugin can be opened
# whether to open disqus
disqus_shortname: chetansachdev
# whether to open the friend comment, fill in the user id of the friend comment
uyan_uid: false
# use or not gitment，https://github.com/imsun/gitment
gitment: false
# gitment:
#   owner:
#   repo:
#   client_id:
#   client_secret:

# use or not Gitalk，https://github.com/gitalk/gitalk
gitalk: false
#  owner: 
#  repo: 
#  client_id: 
#  client_secret: 

# Valine Comment system. https://valine.js.org
valine:
  enable: false # if you want to use Valine，please set the value to true
  appId:  # your leancloud appId
  appKey: # your leancloud appKey
  notify: false # Mail notify
  verify: false # Verify code
  avatar: mp # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  placeholder: 'Write a comment' # Comment Box placeholder
  guest_info: nick,mail,link # Comment header info
  pageSize: 10 # comment list page size

# whether to open Hyper Comments，fill in idEnable，false Disable。http://hypercomments.com
# Hyper Comments support. Write your id here, or false to disable
hyper_id: false

# Speak freely
changyan:
  enable: false
  appid: # your changyan appid
  appkey: # your changyan appkey

# canonical URL
# Let the search engine redirect your sites with different domain names, different subdomains, and different directories in the same domain to the path you expect
# https://support.google.com/webmasters/answer/139066
# assuming the configuration iscanonical: http://imys.net，then from the search engine www.imys.net Entry will redirect to imys.net
canonical: false

# copyright start year
since_year: 2018

# descriptive text related to the author in the user page, if not set to false
about: Javascript engineer, Adobe Flex developer

# “Garlic" visit statistics, see http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  site_uv: Total number of visitors to the site：
  site_pv: Total site visits：

# dynamic definition title
# title_change:
#  normal:(つェ⊂) Hey! Good again!
#  leave: where did the dead go！

# set to true to use the latest theme style of unpkg cdn after publishing
# if you want your custom style to take effect, set this to false
cdn: false

# set to true to use lightbox render image
lightbox: true

# icp record number ICP_license: Beijing ICP No. 1234556-1
ICP_license: false

# Prism Theme, default/coy/okaidia/atom-dark/solarized-light/tomorrow-night
prism:
  theme: tomorrow-night